language: node_js

node_js:
  - 8.9.4

branches:
  only:
    - master

install:
  - npm i

before_script:
  - git config --global user.name 'Sungyub NA'
  - git config --global user.email 'darkerkorean@gmail.com'
  - sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml

script:
  - npm run build