language: node_js

node_js:
  - 8.9.3

branches:
  only:
    - master

before_install:
  - npm i hexo-cli -g

install:
  - npm i

before_script:
  - git config --global user.name 'Sungyub NA'
  - git config --global user.emal 'darkerkorean@gmail.com'
  - sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml

script:
  - npm run build